### ISSUE TITLE
Update PHPMailer

### ISSUE THREAD

**Issue by purplepixie** [purplepixie/freenats#24]
Bundled phpMailer is very out-of-date, update.

**Comment by purplepixie** [comment]
Also confirmed as a breaking bug in new PHP (issue for 1.3x+), error on mail in this case in AA: Fatal error: Uncaught Error: Call to undefined function each() in /opt/freenats/server/base/phpmailer/class.smtp.php:388 Stack trace: #0 /opt/freenats/server/base/phpmailer/class.phpmailer.php(636): SMTP->Data() #1 /opt/freenats/server/base/phpmailer/class.phpmailer.php(511): PHPMailer->SmtpSend() #2 /opt/freenats/server/base/freenats.inc.php(316): PHPMailer->Send() #3 /opt/freenats/server/web/admin.php(151): TFreeNATS->ActionFlush() #4 {main} thrown in /opt/freenats/server/base/phpmailer/class.smtp.php on line 388

**Comment by purplepixie** [comment]
Updated and tested in 1.30.3a
